# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolreviewproject',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='toolreviewproject',
            name='screenshot_filename',
            field=models.FilePathField(blank=True),
        ),
    ]
