# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_review', '0002_auto_20170103_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolreviewproject',
            name='screenshot_filename',
            field=models.FilePathField(blank=True, max_length=500),
        ),
    ]
