# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_review', '0003_auto_20170103_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolreviewproject',
            name='review_video',
        ),
        migrations.AddField(
            model_name='toolreviewproject',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
