# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-08 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_review', '0004_auto_20170104_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolreviewproject',
            name='project_category',
            field=models.CharField(choices=[('GV', 'Government Project'), ('OS', 'Open source project'), ('CO', 'Commercial Product'), ('UN', 'Unclassified'), ('NC', 'Nonprofit Closed Source')], default='UN', max_length=2),
        ),
        migrations.AddField(
            model_name='toolreviewproject',
            name='tool_category',
            field=models.CharField(choices=[('OD', 'Open Data'), ('ED', 'Educational Material'), ('PA', 'Policy Analysis'), ('CL', 'Collaborative Problem-Solving'), ('UN', 'Unclassified')], default='UN', max_length=2),
        ),
    ]
