# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-30 00:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_participationitem_creation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ItemResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandUseParticipationItem',
            fields=[
                ('participationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationItem')),
            ],
            bases=('core.participationitem',),
        ),
        migrations.CreateModel(
            name='LandUseProject',
            fields=[
                ('participationproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationProject')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('feedback_goals', models.ManyToManyField(to='land_use_planning.FeedbackGoal')),
            ],
            bases=('core.participationproject',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TMCQ',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='land_use_planning.Question')),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('option5', models.CharField(max_length=100)),
            ],
            bases=('land_use_planning.question',),
        ),
        migrations.CreateModel(
            name='TMCQResponse',
            fields=[
                ('questionresponse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='land_use_planning.QuestionResponse')),
                ('option_index', models.IntegerField()),
            ],
            bases=('land_use_planning.questionresponse',),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='item_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_use_planning.ItemResponse'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_use_planning.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='feedback_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_use_planning.FeedbackGoal'),
        ),
        migrations.AddField(
            model_name='itemresponse',
            name='participation_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='land_use_planning.LandUseParticipationItem'),
        ),
        migrations.AddField(
            model_name='itemresponse',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
