# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading_assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedassignmentitem',
            name='participation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ParticipationItem'),
        ),
        migrations.AlterField(
            model_name='orderedassignmentitem',
            name='text_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reading_assignment.TextQuestion'),
        ),
    ]
