# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161017_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationproject',
            name='owner_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
            preserve_default=False,
        ),
    ]
