# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_participationitem_display_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationitem',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
