# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_participationitem_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmatch',
            name='has_been_visited',
            field=models.BooleanField(default=False),
        ),
    ]
