# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-24 21:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedmatch_has_been_visited'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GeoTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Tag')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
            ],
            bases=('core.tag',),
        ),
    ]
