# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 04:24
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_geotag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotag',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, srid=4326),
        ),
        migrations.AddField(
            model_name='geotag',
            name='polygon_area',
            field=models.FloatField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
