# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 04:25
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161025_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
