# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-26 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161025_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tag',
            name='detail',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
