# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-29 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_geotag_feature_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationitem',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 29, 16, 54, 15, 469927, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
