# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_participationitem_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotag',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='polygon_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
