# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161109_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
