# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-03 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161214_2131'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name', 'detail')]),
        ),
    ]
