# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-12 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170110_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
