# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-16 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_shortcut'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('issue_type', models.CharField(choices=[('PC', 'Propaganda, campaigning, or biased content'), ('BR', 'Bug or website error'), ('IA', 'Inaccurate content'), ('FR', 'Request a feature')], max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
        ),
    ]
