# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongJobState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField(max_length=300)),
                ('name', models.TextField(max_length=100)),
                ('job_period', models.IntegerField(default=86400)),
                ('job_timeout', models.IntegerField()),
                ('most_recent_update', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='longjobstate',
            unique_together=set([('app_name', 'name')]),
        ),
    ]
