# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-25 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20170421_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('mimetype', models.CharField(default='text/html', max_length=50)),
                ('first_paragraph', models.TextField(blank=True, null=True)),
                ('external_api', models.CharField(blank=True, max_length=100, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
