# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_referencedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencedocument',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
