# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20170523_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='invitation_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='invitation_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
