# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_participationproject_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarks',
            field=models.ManyToManyField(to='core.ParticipationItem'),
        ),
    ]
