# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170113_0205'),
        ('ballot_decider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POVItemResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('point_of_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_decider.PointOfView')),
            ],
        ),
        migrations.CreateModel(
            name='POVToolResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('participation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_decider.BallotDeciderItem')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='povitemresponse',
            name='tool_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot_decider.POVToolResponse'),
        ),
    ]
