# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_decider', '0003_auto_20170127_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofview',
            name='favorability',
        ),
        migrations.AddField(
            model_name='pointofview',
            name='is_favorable',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointofview',
            name='citation_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
