# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-08 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_decider', '0004_auto_20170130_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointofview',
            name='citation_url',
        ),
    ]
