# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-09 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_decider', '0005_remove_pointofview_citation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='povtoolresponse',
            name='final_decision',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
