# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-27 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='bar1_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='bar1_variable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='bar1_x_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='bar1_y_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='bar2_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='bar2_variable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='bar2_x_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='bar2_y_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='csv_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='instructions_note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='methodology_note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='methodology_url',
            field=models.URLField(default='http://betterdem.org'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='pie1_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='pie1_variable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='pie2_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='pie2_variable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='switch_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='switch_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='switch_variable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
