# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-27 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20170113_0205'),
        ('interactive_visualization', '0002_auto_20170127_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivevisualizationproject',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
