# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-09 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeatTheBullshitItem',
            fields=[
                ('participationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationItem')),
            ],
            bases=('core.participationitem',),
        ),
        migrations.CreateModel(
            name='BeatTheBullshitProject',
            fields=[
                ('participationproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationProject')),
                ('topic_overview', models.TextField()),
            ],
            bases=('core.participationproject',),
        ),
        migrations.CreateModel(
            name='Fallacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('example_context', models.TextField()),
                ('example', models.TextField()),
                ('improvement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_string', models.TextField()),
                ('speaker_name', models.CharField(max_length=500)),
                ('reference', models.URLField()),
                ('screenshot_filename', models.FilePathField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beat_the_bullshit.BeatTheBullshitProject')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteFallacyAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('improvement', models.TextField()),
                ('fallacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beat_the_bullshit.Fallacy')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beat_the_bullshit.Quote')),
            ],
        ),
    ]
