# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-09 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_donation'),
        ('beat_the_bullshit', '0002_beatthebullshitproject_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteFallacyQuizItemResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beat_the_bullshit.Fallacy')),
                ('participation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beat_the_bullshit.BeatTheBullshitItem')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
        ),
    ]
