# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-10 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_bullshit', '0003_quotefallacyquizitemresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotefallacyquizitemresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
