# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-11 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_bullshit', '0004_quotefallacyquizitemresponse_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
