# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_the_bullshit', '0005_quote_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatthebullshitproject',
            name='bullet_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatthebullshitproject',
            name='bullet_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beatthebullshitproject',
            name='bullet_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
