# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-06 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city_budgeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('FR', 'Fire and Rescue'), ('PO', 'Police'), ('SW', 'Sewage and Storm Water'), ('LB', 'Library'), ('PR', 'Parks and Recreation'), ('CM', 'Cemetery'), ('WA', 'Water'), ('EG', 'Electric and Gas'), ('GR', 'Garbage and Recycling'), ('TR', 'Transit')], max_length=2)),
                ('source', models.CharField(choices=[('PC', 'Provided by City'), ('PP', 'Provided by Private Companies'), ('PR', 'Provided through Regional Partnership'), ('NP', 'Other / Not Provided')], default='PC', max_length=2)),
                ('expected_expenditure', models.PositiveIntegerField(blank=True)),
                ('city_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_budgeting.CityBudgetingProject')),
            ],
        ),
    ]
