# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-16 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballot_decider', '0006_povtoolresponse_final_decision'),
        ('core', '0027_donation'),
        ('city_budgeting', '0003_auto_20161106_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityBudgetingItem',
            fields=[
                ('participationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationItem')),
            ],
            bases=('core.participationitem',),
        ),
        migrations.CreateModel(
            name='CityBudgetingProject2',
            fields=[
                ('participationproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationProject')),
                ('fiscal_period_start', models.DateField()),
                ('fiscal_period_end', models.DateField()),
                ('budget_json', models.TextField()),
                ('budget_json_version', models.IntegerField(default=1)),
                ('budget_url', models.URLField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GeoTag')),
            ],
            bases=('core.participationproject',),
        ),
        migrations.RemoveField(
            model_name='citybudgetingproject',
            name='city',
        ),
        migrations.RemoveField(
            model_name='citybudgetingproject',
            name='participationproject_ptr',
        ),
        migrations.RemoveField(
            model_name='citybudgetquiz',
            name='participationitem_ptr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='item',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='item_response',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='participation_item',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='service',
            name='city_budget',
        ),
        migrations.RemoveField(
            model_name='tmcq',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='tmcqresponse',
            name='questionresponse_ptr',
        ),
        migrations.DeleteModel(
            name='CityBudgetingProject',
        ),
        migrations.DeleteModel(
            name='CityBudgetQuiz',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionResponse',
        ),
        migrations.DeleteModel(
            name='QuizResponse',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TMCQ',
        ),
        migrations.DeleteModel(
            name='TMCQResponse',
        ),
    ]
