# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-16 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_budgeting', '0004_auto_20170316_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityBudgetingProject2',
            new_name='CityBudgetingProject',
        ),
    ]
