# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-23 18:05
from __future__ import unicode_literals

import city_budgeting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_budgeting', '0005_auto_20170316_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citybudgetingproject',
            name='budget_json',
            field=models.TextField(validators=[city_budgeting.models.validate_budget_json]),
        ),
    ]
