# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_budgeting', '0006_auto_20170323_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='citybudgetingproject',
            name='budget_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='citybudgetingproject',
            name='budget_excel_file',
            field=models.FilePathField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='citybudgetingproject',
            name='expenses_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='citybudgetingproject',
            name='funds_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='citybudgetingproject',
            name='revenues_description',
            field=models.TextField(default=''),
        ),
    ]
