# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_participationproject_owner_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualNewsCurationProject',
            fields=[
                ('participationproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationProject')),
            ],
            bases=('core.participationproject',),
        ),
        migrations.CreateModel(
            name='NewsArticleItem',
            fields=[
                ('participationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationItem')),
                ('url', models.URLField()),
                ('img_url', models.URLField()),
                ('first_paragraph', models.TextField()),
            ],
            bases=('core.participationitem',),
        ),
    ]
