# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-21 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_news_article_curation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticleitem',
            name='first_paragraph',
        ),
        migrations.RemoveField(
            model_name='newsarticleitem',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='newsarticleitem',
            name='url',
        ),
        migrations.AddField(
            model_name='manualnewscurationproject',
            name='first_paragraph',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualnewscurationproject',
            name='img_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualnewscurationproject',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
