# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-13 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0027_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegislatorsItem',
            fields=[
                ('participationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationItem')),
            ],
            bases=('core.participationitem',),
        ),
        migrations.CreateModel(
            name='LegislatorsProject',
            fields=[
                ('participationproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationProject')),
                ('open_states_leg_id', models.CharField(max_length=100)),
                ('open_states_active', models.BooleanField()),
                ('open_states_state', models.CharField(max_length=50)),
                ('photo_url', models.URLField()),
                ('webpage_url', models.URLField()),
                ('chamber', models.CharField(blank=True, choices=[('UP', 'upper'), ('LO', 'lower')], max_length=2, null=True)),
                ('district', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
            ],
            bases=('core.participationproject',),
        ),
    ]
