# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-14 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislatorsproject',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='legislatorsproject',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legislatorsproject',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legislatorsproject',
            name='webpage_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
