# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-17 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_donation'),
        ('legislators', '0005_legislatorsproject_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsItem',
            fields=[
                ('participationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationItem')),
            ],
            bases=('core.participationitem',),
        ),
        migrations.CreateModel(
            name='BillsProject',
            fields=[
                ('participationproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationProject')),
                ('open_states_bill_id', models.CharField(max_length=100)),
                ('bill_id', models.CharField(max_length=100)),
                ('first_action_date', models.DateField(blank=True, null=True)),
                ('last_action_date', models.DateField(blank=True, null=True)),
                ('passed_upper_date', models.DateField(blank=True, null=True)),
                ('passed_lower_date', models.DateField(blank=True, null=True)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('tags', models.ManyToManyField(to='core.Tag')),
            ],
            bases=('core.participationproject',),
        ),
    ]
