# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-29 22:47
from __future__ import unicode_literals

from django.db import migrations
import sys

def copy_last_action_date(apps, schema_editor):
    BI = apps.get_model("legislators", "BillsItem")
    num_items_updated = 0
    for i in BI.objects.all():
        i.last_action_date = i.participation_project.billsproject.last_action_date
        i.save()
        num_items_updated += 1
        if num_items_updated % 1000 == 0:
            sys.stderr.write("migrating legislators.BillsItem #{}\n".format(num_items_updated))
            sys.stderr.flush()

class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0009_auto_20170429_2246'),
    ]

    operations = [
        migrations.RunPython(copy_last_action_date),
    ]
