# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0010_auto_20170429_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsproject',
            name='open_states_bill_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='legislatorsproject',
            name='open_states_leg_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
