# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-11 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0021_auto_20170110_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleQuizItem',
            fields=[
                ('participationitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationItem')),
            ],
            bases=('core.participationitem',),
        ),
        migrations.CreateModel(
            name='SingleQuizProject',
            fields=[
                ('participationproject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ParticipationProject')),
                ('question_text', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100, null=True)),
                ('option4', models.CharField(blank=True, max_length=100, null=True)),
                ('option5', models.CharField(blank=True, max_length=100, null=True)),
                ('correct_answer_index', models.IntegerField()),
                ('citation_url', models.URLField()),
                ('explanation', models.TextField()),
                ('tags', models.ManyToManyField(to='core.Tag')),
            ],
            bases=('core.participationproject',),
        ),
        migrations.CreateModel(
            name='SingleQuizResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('answer_index', models.IntegerField()),
                ('participation_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='single_quiz.SingleQuizItem')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
        ),
    ]
